const testData = {
  feedbackWidgetData: {
    fullName: "Mr. QA Tester",
    email: "name@invalid-qa-email.org",
    message: "This text was generated by Playwright!!!",
    confirmMessageSent: "message sent successfully!",
  },
  indexHtmData: {
    pageTitle: "Ready to Test (QA)",
    introPageCopy: "Welcome to my personal homepage. It's like a peek into my garage",
    introPageCopy2: "Curious about the design choice of this page?",
    weatherAlertLinkText: "View weather alerts on my page",
    weatherAlertHref: "/html/weather-api.htm",
    testSkillsText: "testing skills",
    testSkillsHref: "/html/testing-skills.htm",
    philosophyText: "QA philosophy",
    philosophyHref: "/html/philosophy.htm",
  },
  weatherAlertData: {
    alertTitle: "current watches, warnings, and advisories for nevada",
  },
};

export default testData;
