const testData = {
    
    feedbackWidgetData: {
      fullName: "Mr. QA Tester",
      email: "name@invalid-qa-email.org",
      message: "This text was generated by Playwright!!!",
      confirmMessageSent: "message sent successfully!"
    },
    indexHtmData: {
      pageTitle: "Ready to Test (QA)",
      introPageCopy: "Welcome to my testing ecosystem!",
      introPageCopy2: "Curious about the design choice of this page?",
      weatherAlertLinkText: "View weather alerts on my page",
      weatherAlertHref: "/html/weather-api.htm",
      testSkillsText: "testing skills",
      testSkillsHref: "/html/testing-skills.htm",
      philosophyText: "QA philosophy",
      philosophyHref: "/html/philosophy.htm",

    },
    weatherAlertData: {
      alertTitle: "current watches, warnings, and advisories for alaska"
    }
  };
  
  export default testData;